import { useEffect, useState, useSyncExternalStore } from 'react';

import FormDockPanel from './form-dock-panel';
import ErrorToast from './error-toast';
import {
  type FormDockSnapshot,
  subscribeToSnapshots,
  getSnapshot,
  getServerSnapshot,
} from './plugin/snapshot-source';

/**
 * Defines what types of errors should be captured.
 *
 * - 'all' - thrown (unhandled) errors and console errors.
 * - 'thrown' - only errors thrown inside the application/form, including
 *   unhandled promise rejections.
 * - 'console' - only errors generated by the `console.error` function.
 * - 'none' - do not capture any errors.
 */
export type CapturedErrorLevel = 'all' | 'console' | 'thrown' | 'none';

/**
 * An error pattern value that can be a `string` or a `RegExp` value.
 *
 * Patterns are used to ignore errors by the `FormDock` component.
 */
export type ErrorPattern = string | RegExp;

/**
 * `FormDock` component props.
 */
export type FormDockProps = Readonly<{
  /**
   * The form state snapshot to display.
   *
   * Omit this when the dock is injected by the `form-state-tools` Vite plugin: the
   * dock then subscribes to snapshots pushed over the dev transport via
   * `reportFormState` instead of receiving them as a prop.
   */
  form?: FormDockSnapshot;
  /**
   * Is the application code running in "development" mode?
   *
   * This component if for debugging/observability and should not be rendered
   * in "production" mode.
   *
   * `Only set this property manually if the default component logic is not
   * working correctly in your application.`
   */
  devMode?: boolean;
  /**
   * Should the component be initially rendered in collapsed state? Default: `true`.
   */
  collapsed?: boolean;
  /**
   * Indicates what types of errors should be captured on screen with the error toast?
   *
   * @see {@link CapturedErrorLevel}
   */
  captureErrors?: CapturedErrorLevel;
  /**
   * An array of `string` or `RegExp` values to ignore errors that have a `message` value
   * or a `string` representation that matches one of the patterns.
   *
   * The `collapsed` property value should not be 'none'.
   */
  ignoreErrorPatterns?: ErrorPattern[];
}>;

const EmptyErrorPatterns: ErrorPattern[] = [];

/**
 * A development-only debugging panel that displays detailed information about a form's state.
 *
 * This component renders a form dock only during development or when explicitly enabled via
 * the `devMode` prop. It is completely removed in production builds to avoid any performance impact
 * or exposure of internal form data.
 *
 * @param props - The component props.
 * @param props.form - The current form state response, containing values, errors, touched fields, etc.
 *                     The schema is validated using a Zod object schema.
 * @param props.devMode - Explicitly enable or disable the dock regardless of environment.
 *                        - `true`: always show the dock
 *                        - `false`: never show the dock
 *                        - `undefined`: show only in development environments (default)
 * @param props.collapsed - Is the default state of the dock panel collapsed? Default: `true`.
 * @param props.captureErrors - Should the dock panel display an error toast when an unhandled error is thrown
 *                              or the `console.error` is called? Default: `true`.
 *
 * @returns A form dock component when in development mode, otherwise returns `null`.
 *
 * @example
 * ```tsx
 * <FormDock form={formState} collapsed={false} />
 * ```
 */
function FormDock({
  form,
  devMode,
  collapsed = true,
  captureErrors = 'all',
  ignoreErrorPatterns = EmptyErrorPatterns,
}: FormDockProps) {
  const [isMounted, setIsMounted] = useState(false);

  const transportSnapshot = useSyncExternalStore(
    subscribeToSnapshots,
    getSnapshot,
    getServerSnapshot
  );

  useEffect(() => {
    // SSR workaround
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsMounted(true);
  }, []);

  if (devMode === false || !isMounted) {
    return null;
  }

  const isDevEnvironment =
    devMode === true ||
    (typeof process === 'object' && process.env['NODE_ENV']?.toLowerCase() === 'development');

  if (!isDevEnvironment) {
    return null;
  }

  const snapshot = form ?? transportSnapshot;

  return (
    <>
      {captureErrors !== 'none' && (
        <ErrorToast captureErrors={captureErrors} ignoreErrorPatterns={ignoreErrorPatterns} />
      )}
      {snapshot && <FormDockPanel form={snapshot} collapsed={collapsed} />}
    </>
  );
}

export default FormDock;
